#!/bin/bash
# auto-issue-worker.sh
# Deterministic boilerplate for the auto-issue-worker cron.
# Handles: cd to repo, gh API calls, git branch/commit/push, PR lifecycle
# The LLM agent just needs to make code changes and call this script's helper functions.

set -euo pipefail

REPO_DIR="/home/clawbox/.openclaw/workspace/ClawBox"
GH_REPO="pvyver/ClawBox"

cd "$REPO_DIR"

# Function: find oldest open Phase 2 issue
find_issue() {
  local milestone
  milestone=$(gh api repos/$GH_REPO/milestones --jq '.[] | select(.title | startswith("Phase 2")) | .number')
  if [ -z "$milestone" ]; then
    echo "ERROR: No Phase 2 milestone found" >&2
    exit 1
  fi
  gh api "repos/$GH_REPO/issues?state=open&milestone=$milestone&sort=created&direction=asc&per_page=1" --jq '.[0] | {number, title}'
}

# Function: checkout main and pull
checkout_main() {
  git checkout main && git pull
}

# Function: create branch
create_branch() {
  local name="$1"
  git checkout -b "$name"
}

# Function: commit changes
commit_changes() {
  local msg="$1"
  shift
  git add "$@"
  git commit -m "$msg"
}

# Function: push branch
push_branch() {
  local branch="$1"
  git push origin "$branch"
}

# Function: create PR
create_pr() {
  local branch="$1"
  local num="$2"
  local title="$3"
  gh pr create --repo $GH_REPO --base main --head "$branch" \
    --title "$title" \
    --body "Closes #$num

Auto-generated by Clawie 🦞"
}

# Function: wait for CI and merge
wait_and_merge() {
  local pr_num="$1"
  echo "Waiting for CI on PR #$pr_num..."
  for i in $(seq 1 10); do
    sleep 30
    local state
    state=$(gh api repos/$GH_REPO/pulls/$pr_num --jq '.mergeable_state')
    echo "  (attempt $i/10) mergeable_state: $state"
    if [ "$state" = "clean" ] || [ "$state" = "unstable" ]; then
      echo "  CI looks good, attempting merge..."
      break
    fi
    if [ "$state" = "blocked" ] || [ "$state" = "dirty" ]; then
      echo "  PR is blocked or has conflicts"
      return 1
    fi
  done
  gh pr merge "$pr_num" --repo $GH_REPO --squash --delete-branch
}

# Function: close issue
close_issue() {
  local num="$1"
  gh issue close "$num" --repo $GH_REPO
}

# Function: delete local branch
delete_branch() {
  local branch="$1"
  git branch -D "$branch"
}

echo "auto-issue-worker.sh loaded. Available commands:"
echo "  find_issue                    - Find oldest open Phase 2 issue"
echo "  checkout_main                 - Checkout main and pull"
echo "  create_branch <name>          - Create a branch"
echo "  commit_changes <msg> <files>  - Stage and commit"
echo "  push_branch <name>            - Push branch"
echo "  create_pr <branch> <num> <title> - Create a PR"
echo "  wait_and_merge <pr_num>       - Wait for CI and merge"
echo "  close_issue <num>             - Close an issue"
echo "  delete_branch <name>          - Delete local branch"
